title: Computation as Creative Practice
subtitle:
email: hi@alisa.pizza
description: > # this means to ignore newlines until "baseurl:"
  This workshop introduces novice coders to basic programming concepts, algorithmic approaches to digital design and modelling, and strategies for employing these in artistic practice.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alisay.github.io" # the base hostname & protocol for your site
github:
  repo: "alisay/alisay.github.io"
  branch: "main"


collections:
  articles:
    output: true
permalink: /:path/

# Build settings
markdown: kramdown

redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]

# variables
video: "<span class=\"video-player\"></span>"
assignment: "<span class=\"assignment\">Assignment: </span>"
